version: '3.8'

services:
  user-service:
    build: .
    ports:
      - "5000:5000"
    env_file: 
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
